export const data = {
  result: [
    {
      url: "https://neglected-lever.com/",
      hacker_news_url: "https://low-wasabi.org",
      news_title: "puzzled-item.name",
      posted_on: "2023-01-27T20:05:13.392Z",
      upvotes: 61,
      comments: 36,
    },
    {
      url: "https://best-sugar.name/",
      hacker_news_url: "https://thoughtful-gram.info/",
      news_title: "naughty-opportunity.biz",
      posted_on: "2023-03-21T18:54:41.016Z",
      upvotes: 72,
      comments: 71,
    },
    {
      url: "https://velvety-chit-chat.name",
      hacker_news_url: "https://murky-element.info/",
      news_title: "agitated-availability.com",
      posted_on: "2023-04-04T08:30:05.471Z",
      upvotes: 9,
      comments: 52,
    },
    {
      url: "https://indelible-truth.biz",
      hacker_news_url: "https://genuine-state.org",
      news_title: "polished-interview.org",
      posted_on: "2023-12-13T17:51:43.970Z",
      upvotes: 42,
      comments: 11,
    },
    {
      url: "https://stylish-cappuccino.name/",
      hacker_news_url: "https://practical-durian.org",
      news_title: "big-hearted-abacus.info",
      posted_on: "2023-05-25T04:01:21.172Z",
      upvotes: 27,
      comments: 54,
    },
    {
      url: "https://pointed-haunt.net",
      hacker_news_url: "https://angry-artist.name/",
      news_title: "affectionate-altitude.name",
      posted_on: "2023-07-09T06:53:14.450Z",
      upvotes: 74,
      comments: 50,
    },
    {
      url: "https://idealistic-station.org",
      hacker_news_url: "https://gaseous-infrastructure.biz/",
      news_title: "anchored-limo.info",
      posted_on: "2023-10-29T12:58:37.612Z",
      upvotes: 33,
      comments: 52,
    },
    {
      url: "https://hefty-power.name",
      hacker_news_url: "https://horrible-cartel.org",
      news_title: "rectangular-lid.biz",
      posted_on: "2023-11-18T21:51:49.559Z",
      upvotes: 77,
      comments: 47,
    },
    {
      url: "https://constant-roller.net",
      hacker_news_url: "https://impassioned-hops.net",
      news_title: "trim-facelift.info",
      posted_on: "2023-12-28T14:06:09.668Z",
      upvotes: 18,
      comments: 73,
    },
    {
      url: "https://barren-pod.name",
      hacker_news_url: "https://secondary-onset.com",
      news_title: "unkempt-anguish.com",
      posted_on: "2023-10-19T17:01:57.300Z",
      upvotes: 70,
      comments: 80,
    },
    {
      url: "https://incomplete-paint.info/",
      hacker_news_url: "https://illustrious-hamburger.org/",
      news_title: "useless-selection.info",
      posted_on: "2023-10-22T08:08:23.319Z",
      upvotes: 84,
      comments: 15,
    },
    {
      url: "https://glistening-frog.net/",
      hacker_news_url: "https://measly-choice.org/",
      news_title: "pertinent-ghost.name",
      posted_on: "2023-10-17T15:52:31.291Z",
      upvotes: 47,
      comments: 8,
    },
    {
      url: "https://graceful-peer-to-peer.name",
      hacker_news_url: "https://harmless-incident.biz",
      news_title: "stylish-tone.com",
      posted_on: "2023-07-02T20:51:39.311Z",
      upvotes: 63,
      comments: 19,
    },
    {
      url: "https://droopy-photoreceptor.org",
      hacker_news_url: "https://worthy-manufacturing.org/",
      news_title: "mad-textbook.biz",
      posted_on: "2023-08-08T11:21:40.225Z",
      upvotes: 67,
      comments: 16,
    },
    {
      url: "https://breakable-riddle.com",
      hacker_news_url: "https://kooky-profit.name/",
      news_title: "adept-inventory.biz",
      posted_on: "2023-02-08T19:31:18.705Z",
      upvotes: 3,
      comments: 49,
    },
    {
      url: "https://untrue-rhetoric.org",
      hacker_news_url: "https://shadowy-chasuble.com",
      news_title: "even-dad.biz",
      posted_on: "2023-01-08T11:51:13.889Z",
      upvotes: 81,
      comments: 45,
    },
    {
      url: "https://misguided-dungarees.biz",
      hacker_news_url: "https://enlightened-lava.net",
      news_title: "considerate-paramedic.com",
      posted_on: "2023-09-20T00:19:08.831Z",
      upvotes: 39,
      comments: 74,
    },
    {
      url: "https://pesky-viscose.net",
      hacker_news_url: "https://mixed-yard.name/",
      news_title: "practical-cappelletti.org",
      posted_on: "2023-01-15T01:12:56.157Z",
      upvotes: 42,
      comments: 19,
    },
    {
      url: "https://bogus-steel.info",
      hacker_news_url: "https://dim-robot.net/",
      news_title: "strong-shelf.net",
      posted_on: "2023-07-10T12:51:37.935Z",
      upvotes: 60,
      comments: 79,
    },
    {
      url: "https://growing-hour.name/",
      hacker_news_url: "https://short-term-cousin.biz/",
      news_title: "tedious-phenomenon.net",
      posted_on: "2023-10-08T17:53:40.637Z",
      upvotes: 77,
      comments: 66,
    },
    {
      url: "https://loving-medium.biz/",
      hacker_news_url: "https://livid-oven.org/",
      news_title: "complicated-caffeine.info",
      posted_on: "2023-11-14T08:08:48.215Z",
      upvotes: 21,
      comments: 55,
    },
    {
      url: "https://understated-veranda.com",
      hacker_news_url: "https://extra-small-assistance.info",
      news_title: "good-sentencing.com",
      posted_on: "2023-03-28T04:36:33.394Z",
      upvotes: 81,
      comments: 54,
    },
    {
      url: "https://buttery-workplace.net",
      hacker_news_url: "https://plush-consumer.info/",
      news_title: "teeming-flair.name",
      posted_on: "2023-08-21T19:52:24.342Z",
      upvotes: 4,
      comments: 79,
    },
    {
      url: "https://well-made-moment.biz",
      hacker_news_url: "https://concrete-reversal.org/",
      news_title: "royal-theology.biz",
      posted_on: "2023-12-12T17:50:25.649Z",
      upvotes: 2,
      comments: 23,
    },
    {
      url: "https://cool-charity.com",
      hacker_news_url: "https://extra-small-congo.com/",
      news_title: "lanky-excess.biz",
      posted_on: "2023-08-25T17:24:25.079Z",
      upvotes: 34,
      comments: 28,
    },
    {
      url: "https://enlightened-corner.org/",
      hacker_news_url: "https://reasonable-crocodile.info",
      news_title: "constant-minority.info",
      posted_on: "2023-12-05T16:01:47.847Z",
      upvotes: 46,
      comments: 36,
    },
    {
      url: "https://bronze-bough.name/",
      hacker_news_url: "https://healthy-bump.biz",
      news_title: "tinted-capital.name",
      posted_on: "2023-08-22T11:47:56.656Z",
      upvotes: 82,
      comments: 42,
    },
    {
      url: "https://partial-bud.org",
      hacker_news_url: "https://substantial-detour.name/",
      news_title: "official-blade.net",
      posted_on: "2023-12-05T21:02:12.038Z",
      upvotes: 62,
      comments: 66,
    },
    {
      url: "https://sleepy-drudgery.name",
      hacker_news_url: "https://coarse-electronics.com",
      news_title: "nice-hostess.com",
      posted_on: "2023-09-15T22:27:27.788Z",
      upvotes: 28,
      comments: 15,
    },
    {
      url: "https://equatorial-pickax.biz/",
      hacker_news_url: "https://massive-clothes.name",
      news_title: "unconscious-isogloss.org",
      posted_on: "2023-05-21T19:37:11.072Z",
      upvotes: 51,
      comments: 70,
    },
    {
      url: "https://biodegradable-hatchling.biz/",
      hacker_news_url: "https://remarkable-figurine.org/",
      news_title: "eager-screw-up.net",
      posted_on: "2023-11-17T13:11:12.891Z",
      upvotes: 23,
      comments: 18,
    },
    {
      url: "https://salty-waterwheel.biz",
      hacker_news_url: "https://worried-accountant.name",
      news_title: "exemplary-ribbon.info",
      posted_on: "2023-02-18T05:25:26.039Z",
      upvotes: 60,
      comments: 80,
    },
    {
      url: "https://clever-rubber.org",
      hacker_news_url: "https://far-chronicle.org/",
      news_title: "strange-clarity.biz",
      posted_on: "2023-02-05T02:26:53.607Z",
      upvotes: 65,
      comments: 83,
    },
    {
      url: "https://gripping-routine.name/",
      hacker_news_url: "https://dangerous-particular.com/",
      news_title: "witty-undershirt.biz",
      posted_on: "2023-10-02T14:19:28.127Z",
      upvotes: 83,
      comments: 89,
    },
    {
      url: "https://good-natured-pretzel.net",
      hacker_news_url: "https://compassionate-glass.net/",
      news_title: "creamy-ecosystem.org",
      posted_on: "2023-05-18T00:42:13.120Z",
      upvotes: 20,
      comments: 53,
    },
    {
      url: "https://ready-motor.info/",
      hacker_news_url: "https://medium-silkworm.info",
      news_title: "tattered-lox.org",
      posted_on: "2023-11-04T11:38:25.590Z",
      upvotes: 18,
      comments: 66,
    },
    {
      url: "https://miniature-coinsurance.com",
      hacker_news_url: "https://yawning-pelt.biz",
      news_title: "visible-guacamole.info",
      posted_on: "2023-09-16T14:03:12.327Z",
      upvotes: 7,
      comments: 61,
    },
    {
      url: "https://grimy-outlaw.info",
      hacker_news_url: "https://steep-downforce.net",
      news_title: "imaginative-alliance.com",
      posted_on: "2023-11-22T13:08:50.850Z",
      upvotes: 36,
      comments: 14,
    },
    {
      url: "https://muffled-plasterboard.com/",
      hacker_news_url: "https://quiet-clef.org/",
      news_title: "wee-legislator.biz",
      posted_on: "2023-04-06T09:44:12.023Z",
      upvotes: 65,
      comments: 20,
    },
    {
      url: "https://nervous-husband.name/",
      hacker_news_url: "https://plain-fireman.net",
      news_title: "low-ingredient.biz",
      posted_on: "2023-03-09T08:06:17.101Z",
      upvotes: 83,
      comments: 46,
    },
    {
      url: "https://intrepid-margin.org/",
      hacker_news_url: "https://meek-annual.net/",
      news_title: "big-hearted-boot.com",
      posted_on: "2023-04-07T06:22:12.733Z",
      upvotes: 15,
      comments: 47,
    },
    {
      url: "https://crushing-reporting.biz",
      hacker_news_url: "https://beneficial-wrestler.biz",
      news_title: "compassionate-panel.biz",
      posted_on: "2023-10-31T14:43:07.991Z",
      upvotes: 16,
      comments: 56,
    },
    {
      url: "https://shiny-affair.org",
      hacker_news_url: "https://third-edge.name",
      news_title: "damp-salute.biz",
      posted_on: "2023-06-28T18:08:58.748Z",
      upvotes: 9,
      comments: 15,
    },
    {
      url: "https://hateful-mythology.info",
      hacker_news_url: "https://tall-broad.name/",
      news_title: "grounded-stump.com",
      posted_on: "2023-12-18T11:21:03.680Z",
      upvotes: 34,
      comments: 22,
    },
    {
      url: "https://meek-round.name/",
      hacker_news_url: "https://honest-pyridine.name/",
      news_title: "aromatic-jumbo.org",
      posted_on: "2023-04-07T01:11:16.260Z",
      upvotes: 59,
      comments: 64,
    },
    {
      url: "https://unnatural-show-stopper.org",
      hacker_news_url: "https://spiffy-atrium.net/",
      news_title: "enchanting-tweet.net",
      posted_on: "2023-12-19T08:11:07.623Z",
      upvotes: 17,
      comments: 70,
    },
    {
      url: "https://utter-classification.info/",
      hacker_news_url: "https://carefree-phrase.org",
      news_title: "sticky-perp.info",
      posted_on: "2023-07-23T01:08:38.685Z",
      upvotes: 62,
      comments: 11,
    },
    {
      url: "https://shiny-construction.net/",
      hacker_news_url: "https://dependable-waste.biz/",
      news_title: "colorful-donation.org",
      posted_on: "2023-02-14T02:25:08.268Z",
      upvotes: 7,
      comments: 4,
    },
    {
      url: "https://past-strobe.biz/",
      hacker_news_url: "https://exalted-bidding.net",
      news_title: "bleak-cloud.biz",
      posted_on: "2023-04-16T16:14:19.522Z",
      upvotes: 8,
      comments: 55,
    },
    {
      url: "https://grim-councilor.info",
      hacker_news_url: "https://austere-peach.net",
      news_title: "indolent-left.biz",
      posted_on: "2023-07-01T19:12:48.428Z",
      upvotes: 8,
      comments: 27,
    },
    {
      url: "https://early-wedding.com",
      hacker_news_url: "https://suburban-population.name",
      news_title: "cruel-councilperson.name",
      posted_on: "2023-11-04T14:27:36.271Z",
      upvotes: 74,
      comments: 15,
    },
    {
      url: "https://playful-cartilage.info/",
      hacker_news_url: "https://thrifty-plant.biz/",
      news_title: "ornery-pleasure.biz",
      posted_on: "2023-01-05T02:42:24.782Z",
      upvotes: 81,
      comments: 21,
    },
    {
      url: "https://possible-campus.info/",
      hacker_news_url: "https://sizzling-alpenhorn.biz",
      news_title: "cheery-chord.name",
      posted_on: "2023-05-23T09:30:27.963Z",
      upvotes: 24,
      comments: 28,
    },
    {
      url: "https://clever-driveway.net",
      hacker_news_url: "https://quaint-toot.net/",
      news_title: "white-actor.biz",
      posted_on: "2023-09-15T10:56:10.403Z",
      upvotes: 10,
      comments: 60,
    },
    {
      url: "https://hefty-stomach.net/",
      hacker_news_url: "https://striped-macadamia.net",
      news_title: "shocking-theory.com",
      posted_on: "2023-08-09T23:20:11.192Z",
      upvotes: 26,
      comments: 81,
    },
    {
      url: "https://honest-houseboat.biz",
      hacker_news_url: "https://fancy-heyday.net/",
      news_title: "blue-signup.info",
      posted_on: "2023-09-14T02:47:53.031Z",
      upvotes: 69,
      comments: 72,
    },
    {
      url: "https://neglected-doubter.name",
      hacker_news_url: "https://polished-signet.info/",
      news_title: "soupy-sidecar.org",
      posted_on: "2023-10-02T23:26:16.999Z",
      upvotes: 25,
      comments: 78,
    },
    {
      url: "https://internal-eye.org/",
      hacker_news_url: "https://spanish-professor.com/",
      news_title: "pushy-drake.biz",
      posted_on: "2023-07-07T00:11:32.100Z",
      upvotes: 76,
      comments: 65,
    },
    {
      url: "https://spirited-memo.biz",
      hacker_news_url: "https://negligible-tennis.name",
      news_title: "happy-go-lucky-dot.biz",
      posted_on: "2023-06-18T19:17:05.836Z",
      upvotes: 25,
      comments: 32,
    },
    {
      url: "https://lone-convertible.org/",
      hacker_news_url: "https://hungry-cape.net/",
      news_title: "huge-cloak.com",
      posted_on: "2023-09-11T16:48:17.829Z",
      upvotes: 11,
      comments: 47,
    },
    {
      url: "https://joint-linkage.name",
      hacker_news_url: "https://handsome-rating.com",
      news_title: "beneficial-server.info",
      posted_on: "2023-05-23T16:20:15.258Z",
      upvotes: 73,
      comments: 72,
    },
    {
      url: "https://unwieldy-flexibility.org/",
      hacker_news_url: "https://antique-estuary.org",
      news_title: "bold-cloister.net",
      posted_on: "2023-04-16T00:03:31.540Z",
      upvotes: 70,
      comments: 82,
    },
    {
      url: "https://golden-ottoman.org/",
      hacker_news_url: "https://faithful-night.com/",
      news_title: "weighty-tray.org",
      posted_on: "2023-07-03T08:52:33.123Z",
      upvotes: 50,
      comments: 25,
    },
    {
      url: "https://thunderous-knuckle.biz",
      hacker_news_url: "https://hard-to-find-shear.net/",
      news_title: "far-flung-anybody.name",
      posted_on: "2023-09-19T12:47:26.417Z",
      upvotes: 11,
      comments: 58,
    },
    {
      url: "https://passionate-parser.biz",
      hacker_news_url: "https://brief-adjustment.com/",
      news_title: "heavy-ligula.info",
      posted_on: "2023-02-14T20:33:02.315Z",
      upvotes: 5,
      comments: 38,
    },
    {
      url: "https://guilty-cross-stitch.com/",
      hacker_news_url: "https://organic-viability.info",
      news_title: "rusty-grease.net",
      posted_on: "2023-02-13T13:48:29.178Z",
      upvotes: 24,
      comments: 22,
    },
    {
      url: "https://square-tile.org/",
      hacker_news_url: "https://coarse-gaming.name/",
      news_title: "far-off-universe.name",
      posted_on: "2023-06-04T10:46:44.948Z",
      upvotes: 44,
      comments: 80,
    },
    {
      url: "https://vague-gelatin.name",
      hacker_news_url: "https://sugary-journalist.com/",
      news_title: "willing-brick.net",
      posted_on: "2023-07-11T00:16:14.176Z",
      upvotes: 65,
      comments: 13,
    },
    {
      url: "https://flustered-leather.name/",
      hacker_news_url: "https://normal-cabin.net",
      news_title: "whopping-media.info",
      posted_on: "2023-08-19T18:15:26.218Z",
      upvotes: 59,
      comments: 41,
    },
    {
      url: "https://knobby-tab.name",
      hacker_news_url: "https://ecstatic-whisker.biz/",
      news_title: "rubbery-crystal.info",
      posted_on: "2023-06-02T22:58:40.703Z",
      upvotes: 49,
      comments: 67,
    },
    {
      url: "https://blank-wash.org",
      hacker_news_url: "https://shameless-cannibal.com",
      news_title: "starchy-cluster.biz",
      posted_on: "2023-07-28T18:59:22.108Z",
      upvotes: 53,
      comments: 42,
    },
    {
      url: "https://entire-suffocation.name/",
      hacker_news_url: "https://masculine-visitor.biz",
      news_title: "coarse-tune-up.org",
      posted_on: "2023-04-03T22:29:48.221Z",
      upvotes: 29,
      comments: 86,
    },
    {
      url: "https://spry-witch-hunt.com",
      hacker_news_url: "https://unaware-panic.org/",
      news_title: "grim-sonnet.net",
      posted_on: "2023-11-04T20:44:17.092Z",
      upvotes: 52,
      comments: 73,
    },
    {
      url: "https://jealous-spill.biz/",
      hacker_news_url: "https://sandy-fish.name",
      news_title: "rectangular-raisin.net",
      posted_on: "2023-03-16T19:09:01.518Z",
      upvotes: 1,
      comments: 53,
    },
    {
      url: "https://half-highland.com/",
      hacker_news_url: "https://tricky-billion.net",
      news_title: "evil-offer.info",
      posted_on: "2023-06-13T20:38:11.381Z",
      upvotes: 76,
      comments: 28,
    },
    {
      url: "https://circular-maximum.com/",
      hacker_news_url: "https://yellowish-hook.info/",
      news_title: "genuine-balaclava.com",
      posted_on: "2023-09-18T03:48:51.382Z",
      upvotes: 55,
      comments: 87,
    },
    {
      url: "https://metallic-ottoman.net",
      hacker_news_url: "https://dearest-hydrolysis.biz/",
      news_title: "opulent-cytoplasm.org",
      posted_on: "2023-08-09T14:26:20.434Z",
      upvotes: 62,
      comments: 52,
    },
    {
      url: "https://steel-usage.com/",
      hacker_news_url: "https://purple-salute.org/",
      news_title: "made-up-precedent.name",
      posted_on: "2023-02-09T12:21:07.154Z",
      upvotes: 21,
      comments: 38,
    },
    {
      url: "https://woeful-ownership.name",
      hacker_news_url: "https://trusty-prophet.info",
      news_title: "first-metabolite.biz",
      posted_on: "2023-08-24T00:19:31.203Z",
      upvotes: 13,
      comments: 3,
    },
    {
      url: "https://offbeat-stall.name",
      hacker_news_url: "https://dapper-paint.biz/",
      news_title: "jaded-pantologist.com",
      posted_on: "2023-06-06T09:16:39.840Z",
      upvotes: 36,
      comments: 63,
    },
    {
      url: "https://metallic-independence.info/",
      hacker_news_url: "https://offbeat-icing.org",
      news_title: "blushing-inversion.info",
      posted_on: "2023-05-11T14:58:49.636Z",
      upvotes: 33,
      comments: 9,
    },
    {
      url: "https://colorful-series.info",
      hacker_news_url: "https://cheap-viability.com/",
      news_title: "blind-fear.name",
      posted_on: "2023-04-24T11:46:35.018Z",
      upvotes: 5,
      comments: 82,
    },
    {
      url: "https://easy-contractor.net/",
      hacker_news_url: "https://blaring-picnic.biz/",
      news_title: "dearest-mat.net",
      posted_on: "2023-05-01T00:25:20.120Z",
      upvotes: 75,
      comments: 59,
    },
    {
      url: "https://fearful-shirtdress.com/",
      hacker_news_url: "https://third-trustee.org",
      news_title: "squeaky-brooch.info",
      posted_on: "2023-03-20T11:54:24.330Z",
      upvotes: 84,
      comments: 50,
    },
    {
      url: "https://insubstantial-hundred.name/",
      hacker_news_url: "https://every-intestine.info",
      news_title: "suspicious-tunnel.name",
      posted_on: "2023-01-05T07:52:50.619Z",
      upvotes: 28,
      comments: 81,
    },
    {
      url: "https://naive-bacon.com",
      hacker_news_url: "https://modest-hacksaw.com/",
      news_title: "steel-major-league.net",
      posted_on: "2023-10-10T16:39:48.810Z",
      upvotes: 33,
      comments: 30,
    },
    {
      url: "https://lopsided-cornerstone.com",
      hacker_news_url: "https://virtuous-anorak.info/",
      news_title: "frizzy-reset.info",
      posted_on: "2023-06-30T04:04:43.564Z",
      upvotes: 90,
      comments: 26,
    },
    {
      url: "https://staid-tradition.info",
      hacker_news_url: "https://criminal-residue.net",
      news_title: "bold-pickup.biz",
      posted_on: "2023-10-29T10:54:52.290Z",
      upvotes: 13,
      comments: 66,
    },
    {
      url: "https://angry-dimension.net/",
      hacker_news_url: "https://high-level-die.info",
      news_title: "bountiful-topic.net",
      posted_on: "2023-12-19T15:28:45.117Z",
      upvotes: 38,
      comments: 71,
    },
    {
      url: "https://plain-sunroom.net",
      hacker_news_url: "https://early-underpass.biz/",
      news_title: "gargantuan-waitress.com",
      posted_on: "2023-07-09T12:41:02.099Z",
      upvotes: 33,
      comments: 6,
    },
  ],
};
